RotatingCube: /home/benny/Desktop/Projects/C/Rotating Cube/X_Rotating_Cube/src/c_graphics.c File Reference
c_graphics.c File Reference
#include "c_graphics.h"
Functions
Vec2 projection_2d (Vec3 vert, int scr_width, int scr_height)
Function Documentation
projection_2d()
Vec2 projection_2d (Vec3 vert, int scr_width, int scr_height)
Definition at line 10 of file c_graphics.c.
References Vec3::x, Vec3::y, and Vec3::z.
Referenced by draw_edges(), draw_faces(), and draw_verticies().