RotatingCube: /home/benny/Desktop/Projects/C/Rotating Cube/X_Rotating_Cube/src/canvas.c File Reference
canvas.c File Reference
#include "canvas.h"
Functions
void canvas_init (String *cnv)
void new_str (String *n_str, const char *str_in)
size_t str_len (const char *str)
void draw (String str)
void free_canvas (String *cnv)
void free_string (String *n_str)
void cls (void)
Function Documentation
canvas_init()
void canvas_init (String * cnv)
Definition at line 11 of file canvas.c.
References CANVAS_BACKGROUND_CH, H_MAX, new_str(), and V_MAX.
Referenced by main().
cls()
void cls (void)
Definition at line 86 of file canvas.c.
Referenced by update().
draw()
void draw (String str)
Definition at line 54 of file canvas.c.
References String::len, and String::str.
Referenced by update().
free_canvas()
void free_canvas (String * cnv)
Definition at line 65 of file canvas.c.
References free_string(), and V_MAX.
Referenced by main().
free_string()
void free_string (String * n_str)
Definition at line 73 of file canvas.c.
References String::str.
Referenced by free_canvas().
new_str()
void new_str (String * n_str, const char * str_in)
Definition at line 29 of file canvas.c.
References String::len, String::str, and str_len().
Referenced by canvas_init().
str_len()
size_t str_len (const char * str)
Definition at line 41 of file canvas.c.
Referenced by new_str().