RotatingCube: /home/benny/Desktop/Projects/C/Rotating Cube/X_Rotating_Cube/inc/cube.h File Reference
cube.h File Reference
#include "vec.h"
#include "canvas.h"
#include "c_graphics.h"
#include <math.h>
Data Structures
struct Cube
Typedefs
typedef char AsciiOperation(int)
Functions
void cube_init (Cube *c)
initializes the cube to unit cube and zero rotation
void rotate (Cube *cnv)
rotatest the cube according to its rotation vector
void draw_cube (String *cnv, Cube *c)
Draws the cube on the canvas.
void draw_verticies (String *cnv, Cube *c, char ch, int n_vert)
Draws the vertices of the cube on the canvas.
void draw_edges (String *cnv, Cube *c, char ch, int n_edges)
Draws the edges of the cube on the canvas.
void draw_faces (String *cnv, Cube *c, AsciiOperation *ascii_fun, int n_faces)
Draws the faces of the cube on the canvas.
Typedef Documentation
AsciiOperation
typedef char AsciiOperation(int)
Definition at line 16 of file cube.h.
Function Documentation
cube_init()
void cube_init (Cube * c)
initializes the cube to unit cube and zero rotation
Precondition
Postcondition
Parameters
c
Definition at line 63 of file cube.c.
References Cube::rotation, UNIT_CUBE, Cube::vertex, Vec3::x, Vec3::y, and Vec3::z.
Referenced by main().
draw_cube()
void draw_cube (String * cnv, Cube * c)
Draws the cube on the canvas.
Precondition
Postcondition
Parameters
cnv
c
Definition at line 114 of file cube.c.
References draw_faces(), SEQUENCIAL, and set_ascii_operation().
Referenced by update().
draw_edges()
void draw_edges (String * cnv, Cube * c, char ch, int n_edges)
Draws the edges of the cube on the canvas.
Precondition
Postcondition
Parameters
cnv
c
ch
n_edges
Definition at line 169 of file cube.c.
References addVec2(), Cube::edge, mulVec2Scalar(), normVec2(), projection_2d(), String::str, subVec2(), UNIT_CUBE, Cube::vertex, Vec2::x, and Vec2::z.
draw_faces()
void draw_faces (String * cnv, Cube * c, AsciiOperation * ascii_fun, int n_faces)
Draws the faces of the cube on the canvas.
This function uses a scanline triangle fill algorithm to rasterize each face of the cube. It first performs back-face culling to skip faces that are not visible from the camera's perspective. CULL_LIM defines the threshold for culling based on the dot product between the face normal and camera position.
Precondition
Postcondition
Parameters
cnv
c
ascii_fun
n_faces
Definition at line 216 of file cube.c.
References CAMERA_POS, crossVec3(), CULL_LIM, dotVec3(), EPSILON, Cube::faces, projection_2d(), subVec3(), UNIT_CUBE, Cube::vertex, Vec2::x, Vec3::x, Vec3::y, Vec2::z, and Vec3::z.
Referenced by draw_cube().
draw_verticies()
void draw_verticies (String * cnv, Cube * c, char ch, int n_vert)
Draws the vertices of the cube on the canvas.
Precondition
Postcondition
Parameters
cnv
c
ch
n_vert
Definition at line 145 of file cube.c.
References projection_2d(), Cube::vertex, and Vec2::x.
rotate()
void rotate (Cube * cnv)
rotatest the cube according to its rotation vector
Precondition
Postcondition
Parameters
cnv
Definition at line 84 of file cube.c.
References Cube::rotation, UNIT_CUBE, Cube::vertex, Vec3::x, Vec3::y, and Vec3::z.
Referenced by main().