RotatingCube: /home/benny/Desktop/Projects/C/Rotating Cube/X_Rotating_Cube/src/cube.c File Reference
cube.c File Reference
#include "cube.h"
#include "vec.h"
Macros
#define EDGE_ASCII_CH '.'
#define VRTX_ASCII_CH 'X'
#define EPSILON 1e-3
#define CULL_LIM 3.2
#define CAMERA_POS {0.0, 0.0, 2.0}
Enumerations
enum AsciiOperations { SEQUENCIAL = 1 }
Functions
static char get_ascii_symbol (int symbol)
static void set_ascii_operation (int operation, AsciiOperation **func_ptr)
void cube_init (Cube *c)
initializes the cube to unit cube and zero rotation
void rotate (Cube *cnv)
rotatest the cube according to its rotation vector
void draw_cube (String *cnv, Cube *c)
Draws the cube on the canvas.
void draw_verticies (String *cnv, Cube *c, char ch, int n_vert)
Draws the vertices of the cube on the canvas.
void draw_edges (String *cnv, Cube *c, char ch, int n_edges)
Draws the edges of the cube on the canvas.
void draw_faces (String *cnv, Cube *c, AsciiOperation *ascii_fun, int n_faces)
Draws the faces of the cube on the canvas.
Variables
const Cube UNIT_CUBE
Macro Definition Documentation
CAMERA_POS
#define CAMERA_POS {0.0, 0.0, 2.0}
Definition at line 16 of file cube.c.
CULL_LIM
#define CULL_LIM 3.2
Definition at line 15 of file cube.c.
EDGE_ASCII_CH
#define EDGE_ASCII_CH '.'
Definition at line 10 of file cube.c.
EPSILON
#define EPSILON 1e-3
Definition at line 13 of file cube.c.
VRTX_ASCII_CH
#define VRTX_ASCII_CH 'X'
Definition at line 11 of file cube.c.
Enumeration Type Documentation
AsciiOperations
enum AsciiOperations
Enumerator
SEQUENCIAL
Definition at line 21 of file cube.c.
Function Documentation
cube_init()
void cube_init (Cube * c)
initializes the cube to unit cube and zero rotation
Precondition
Postcondition
Parameters
c
Definition at line 63 of file cube.c.
References Cube::rotation, UNIT_CUBE, Cube::vertex, Vec3::x, Vec3::y, and Vec3::z.
Referenced by main().
draw_cube()
void draw_cube (String * cnv, Cube * c)
Draws the cube on the canvas.
Precondition
Postcondition
Parameters
cnv
c
Definition at line 114 of file cube.c.
References draw_faces(), SEQUENCIAL, and set_ascii_operation().
Referenced by update().
draw_edges()
void draw_edges (String * cnv, Cube * c, char ch, int n_edges)
Draws the edges of the cube on the canvas.
Precondition
Postcondition
Parameters
cnv
c
ch
n_edges
Definition at line 169 of file cube.c.
References addVec2(), Cube::edge, mulVec2Scalar(), normVec2(), projection_2d(), String::str, subVec2(), UNIT_CUBE, Cube::vertex, Vec2::x, and Vec2::z.
draw_faces()
void draw_faces (String * cnv, Cube * c, AsciiOperation * ascii_fun, int n_faces)
Draws the faces of the cube on the canvas.
This function uses a scanline triangle fill algorithm to rasterize each face of the cube. It first performs back-face culling to skip faces that are not visible from the camera's perspective. CULL_LIM defines the threshold for culling based on the dot product between the face normal and camera position.
Precondition
Postcondition
Parameters
cnv
c
ascii_fun
n_faces
Definition at line 216 of file cube.c.
References CAMERA_POS, crossVec3(), CULL_LIM, dotVec3(), EPSILON, Cube::faces, projection_2d(), subVec3(), UNIT_CUBE, Cube::vertex, Vec2::x, Vec3::x, Vec3::y, Vec2::z, and Vec3::z.
Referenced by draw_cube().
draw_verticies()
void draw_verticies (String * cnv, Cube * c, char ch, int n_vert)
Draws the vertices of the cube on the canvas.
Precondition
Postcondition
Parameters
cnv
c
ch
n_vert
Definition at line 145 of file cube.c.
References projection_2d(), Cube::vertex, and Vec2::x.
get_ascii_symbol()
static char get_ascii_symbol (int symbol) static
Definition at line 344 of file cube.c.
Referenced by set_ascii_operation().
rotate()
void rotate (Cube * cnv)
rotatest the cube according to its rotation vector
Precondition
Postcondition
Parameters
cnv
Definition at line 84 of file cube.c.
References Cube::rotation, UNIT_CUBE, Cube::vertex, Vec3::x, Vec3::y, and Vec3::z.
Referenced by main().
set_ascii_operation()
static void set_ascii_operation (int operation, AsciiOperation ** func_ptr) static
Definition at line 366 of file cube.c.
References get_ascii_symbol(), and SEQUENCIAL.
Referenced by draw_cube().
Variable Documentation
UNIT_CUBE
const Cube UNIT_CUBE
Initial value:
=
{
    .vertex =
    {
        {-1,1,1},{1,1,1},{-1,-1,1},{1,-1,1},
        {-1,-1,-1}, {1,-1,-1}, {1,1,-1}, {-1,1,-1}
    },
    .edge =
    {
        {0,1},{2,3},{3,1},{2,0},
        {5,6},{5,3},{1,6},{4,5},
        {4,2},{6,7},{7,0},{4,7},
    },
    .faces =
    {
        {5,4,7}, {6,5,7},{0,2,3}, {1,0,3},
        {3,2,4}, {3,4,5},{2,0,4}, {4,0,7},
        {0,1,7}, {1,6,7},{1,3,5}, {1,5,6}
    }
}
Definition at line 32 of file cube.c.
Referenced by cube_init(), draw_edges(), draw_faces(), and rotate().