RotatingCube: /home/benny/Desktop/Projects/C/Rotating Cube/X_Rotating_Cube/src/main.c File Reference
main.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <math.h>
#include "vec.h"
#include "cube.h"
#include "canvas.h"
Macros
#define ROT_STEP 32
Functions
static void update (String *canvas, Cube *cube)
int main (void)
Macro Definition Documentation
ROT_STEP
#define ROT_STEP 32
Definition at line 11 of file main.c.
Function Documentation
main()
int main (void)
Definition at line 17 of file main.c.
References canvas_init(), cube_init(), free_canvas(), ROT_STEP, rotate(), Cube::rotation, update(), V_MAX, Vec3::x, Vec3::y, and Vec3::z.
update()
static void update (String * canvas, Cube * cube) static
Definition at line 52 of file main.c.
References cls(), draw(), draw_cube(), and V_MAX.
Referenced by main().