RotatingCube: /home/benny/Desktop/Projects/C/Rotating Cube/X_Rotating_Cube/src/vec.c File Reference
vec.c File Reference
#include "math.h"
Data Structures
struct Vec2
struct Vec3
Functions
Vec3 addVec3 (Vec3 a, Vec3 b)
adds two 3D vectors element wise
Vec2 addVec2 (Vec2 a, Vec2 b)
adds two 2D vectors element wise
Vec3 subVec3 (Vec3 a, Vec3 b)
subtracts two 3D vectors element wise
Vec2 subVec2 (Vec2 a, Vec2 b)
subtracts two 2D vectors element wise
Vec3 mulVec3 (Vec3 a, Vec3 b)
element wise multiply two 3D vectors
Vec2 mulVec2 (Vec2 a, Vec2 b)
element wise multiply two 2D vectors
Vec3 mulVec3Scalar (Vec3 v, double s)
Multiply 3D vector by an integer scalar.
Vec2 mulVec2Scalar (Vec2 v, double s)
Multiply 2D vector by an integer scalar.
Vec3 divVec3 (Vec3 a, Vec3 b)
element wise division of two 3D vectors
Vec2 divVec2 (Vec2 a, Vec2 b)
element wise division of two 2D vectors
Vec3 crossVec3 (Vec3 a, Vec3 b)
Cross product of two 3D vectors.
double normVec3 (Vec3 v)
calculates the euclidean norm of a 3D vector
double normVec2 (Vec2 v)
calculates the euclidean norm of a 2D vector
double dotVec3 (Vec3 a, Vec3 b)
Dot product of two 3D vectors.
Function Documentation
addVec2()
Vec2 addVec2 (Vec2 a, Vec2 b)
adds two 2D vectors element wise
Precondition
Postcondition
Parameters
a
b
Returns
Definition at line 42 of file vec.c.
References Vec2::x, and Vec2::z.
Referenced by draw_edges().
addVec3()
Vec3 addVec3 (Vec3 a, Vec3 b)
adds two 3D vectors element wise
Precondition
Postcondition
Parameters
a
b
Returns
Definition at line 23 of file vec.c.
References Vec3::x, Vec3::y, and Vec3::z.
crossVec3()
Vec3 crossVec3 (Vec3 a, Vec3 b)
Cross product of two 3D vectors.
Precondition
Postcondition
Parameters
a
b
Returns
Definition at line 206 of file vec.c.
References Vec3::x, Vec3::y, and Vec3::z.
Referenced by draw_faces().
divVec2()
Vec2 divVec2 (Vec2 a, Vec2 b)
element wise division of two 2D vectors
Precondition
Postcondition
Parameters
a
b
Returns
Definition at line 188 of file vec.c.
References Vec2::x, and Vec2::z.
divVec3()
Vec3 divVec3 (Vec3 a, Vec3 b)
element wise division of two 3D vectors
Precondition
Postcondition
Parameters
a
b
Returns
Definition at line 169 of file vec.c.
References Vec3::x, Vec3::y, and Vec3::z.
dotVec3()
double dotVec3 (Vec3 a, Vec3 b)
Dot product of two 3D vectors.
Precondition
Postcondition
Parameters
a
b
Returns
Definition at line 253 of file vec.c.
References Vec3::x, Vec3::y, and Vec3::z.
Referenced by draw_faces().
mulVec2()
Vec2 mulVec2 (Vec2 a, Vec2 b)
element wise multiply two 2D vectors
Precondition
Postcondition
Parameters
a
b
Returns
Definition at line 116 of file vec.c.
References Vec2::x, and Vec2::z.
mulVec2Scalar()
Vec2 mulVec2Scalar (Vec2 v, double s)
Multiply 2D vector by an integer scalar.
Precondition
Postcondition
Parameters
v
s
Returns
Definition at line 152 of file vec.c.
References Vec2::x, and Vec2::z.
Referenced by draw_edges().
mulVec3()
Vec3 mulVec3 (Vec3 a, Vec3 b)
element wise multiply two 3D vectors
Precondition
Postcondition
Parameters
a
b
Returns
Definition at line 97 of file vec.c.
References Vec3::x, Vec3::y, and Vec3::z.
mulVec3Scalar()
Vec3 mulVec3Scalar (Vec3 v, double s)
Multiply 3D vector by an integer scalar.
Precondition
Postcondition
Parameters
v
s
Returns
Definition at line 134 of file vec.c.
References Vec3::x, Vec3::y, and Vec3::z.
normVec2()
double normVec2 (Vec2 v)
calculates the euclidean norm of a 2D vector
Precondition
Postcondition
Parameters
v
Returns
Definition at line 236 of file vec.c.
References Vec2::x, and Vec2::z.
Referenced by draw_edges().
normVec3()
double normVec3 (Vec3 v)
calculates the euclidean norm of a 3D vector
Precondition
Postcondition
Parameters
v
Returns
Definition at line 220 of file vec.c.
References Vec3::x, Vec3::y, and Vec3::z.
subVec2()
Vec2 subVec2 (Vec2 a, Vec2 b)
subtracts two 2D vectors element wise
Precondition
Postcondition
Parameters
a
b
Returns
Definition at line 79 of file vec.c.
References Vec2::x, and Vec2::z.
Referenced by draw_edges().
subVec3()
Vec3 subVec3 (Vec3 a, Vec3 b)
subtracts two 3D vectors element wise
Precondition
Postcondition
Parameters
a
b
Returns
Definition at line 60 of file vec.c.
References Vec3::x, Vec3::y, and Vec3::z.
Referenced by draw_faces().